<div class="container-fluid iw_section" id="sectionjrimv9z0">
			<div class="row iw_row iw_stretch" id="rowjrimv9z1">
				<div class="iw_columns col-lg-12" id="coljrimv9z2">
					<div class="iw_component" id="iw_comp1548819042875">





						<div class="footer-box">
							<div class="footer-component">
								<div class="footer-caution">
									*Prices, promotions and availability may vary by store and online. Prices subject to change without
									notice. Quantities are limited. Check with your local retailers for final price and availability.
								</div>
							</div>
						</div>


						<div class="footer-box">
							<div class="footer-component">
								<div class="footer-caution">
									<div class="caution-wrap">
										<div id="pdpArea" class="caution-text">
											LG TV, Computers, Appliances. <br><br>Life's about more than having the latest technology. It’s
											about the experiences technology creates. From TVs and refrigerators to cell phones and computer
											monitors, LG UK delivers home electronics that let you embrace life and prepare you for its
											greatest moments. <br>LG Electronics UK designs products that are intuitive, responsive and more
											eco-friendly, so you can spend wisely, be more productive and reduce the impact on the world
											around you. We’re committed to providing home electronics that work best for the way you live and
											to keeping you updated with the latest technological advances. After all, life’s better when
											you’re prepared.
										</div>
										<button type="button" name="button" aria-expanded="false" aria-controls="pdpArea" class="btn-more"
											data-text="More,Close">More</button>
									</div>
								</div>
							</div>
						</div>


						<div class="footer-box">
							<footer class="footer-main-contents">
								<div class="hidden-mobile">
									<div class="skip_nav"> <a href="#lgSkipToSitemap" data-link-area="footer-skip_to_sitemap"
											data-link-name="">Skip to Sitemap</a> </div>
									<div class="footer-component">
										<ul class="footer-contents cs-area">
											<li class="footer-contents-box phone-support">
												<div class="box-wrap">
													<div class="footer-title"><span class="no-link">
															<h5>Phone Support</h5>
														</span></div>
													<div class="support-text"><span>Consumer Support</span><span>Monday to Friday, 9:00am to
															5:00pm</span><span>Saturday, 9:00am to 3:00pm </span><span>Closed: Sunday and Bank
															Holidays</span><span><a href="tel:03448475454" style="text-decoration:none">UK : 0344 847
																5454</a></span><span>IE : 01 686 9454</span></div>
													<div class="support-text"><span>Commercial Support</span><span>Exclusively for Air
															Conditioning and Heating</span><span><a href="tel:08448471402"
																style="text-decoration:none">UK : 08448 471 402</a>option 4</span><span><a
																href="tel:0919274459" style="text-decoration:none">Ireland : 0919 274 459</a></span>
													</div>
												</div>
											</li>
											<li class="footer-contents-box">
												<div class="box-wrap">
													<div class="footer-title"><a href="https://www.lg.com/uk/support/chat-email"
															data-link-area="footer-chat_&amp;_email" data-link-name="chat_&amp;_email">Email
															Support</a></div>
												</div>
											</li>
										</ul>
									</div>
									<div class="footer-component">
										<div class="footer-contents">
											<ul class="footer-contents-box column-3">
												<li class="link-wrap">
													<div class="footer-title"><a href="https://www.lg.com/uk/tv-audio-video"
															data-link-area="footer-super_category" data-link-name="tv/audio/video">
															<h5>TV/Audio/Video</h5>
														</a></div>
													<ul>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/tvs"
																data-link-area="footer-category" data-link-name="tvs">
																<h6>TVs</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/speakers-sound-systems"
																data-link-area="footer-category" data-link-name="speakers_&amp;_sound_systems">
																<h6>Speakers &amp; Sound Systems</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/blu-ray-dvd-players"
																data-link-area="footer-category" data-link-name="blu-ray-dvd_players">
																<h6>Blu-ray &amp; DVD Players</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/projectors"
																data-link-area="footer-category" data-link-name="projectors">PROJECTORS</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/home-cinema-systems"
																data-link-area="footer-category" data-link-name="home_cinema_systems">Home Cinema
																Systems</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/true-wireless-earbuds"
																data-link-area="footer-category" data-link-name="true_wireless_earbuds">
																<h6>True Wireless Earbuds</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/tv-accessories"
																data-link-area="footer-category" data-link-name="tv_accessories">
																<h6>TV Accessories</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://gb.lgappstv.com/main?lang=eng_GB"
																data-link-area="footer-category" data-link-name="lg_content_store(tv)"
																class="link-text ico-blank" target="_blank" title="Opens in a new window">LG Content
																Store(TV)</a>
														</li>
														<li class="footer-sub-title"><span class="no-link">
																<h6>Buying Guide</h6>
															</span></li>
													</ul>
												</li>
												<li class="link-wrap">
													<div class="footer-title"><a href="https://www.lg.com/uk/appliances"
															data-link-area="footer-super_category" data-link-name="appliances">
															<h5>Appliances</h5>
														</a></div>
													<ul>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/washing-machines"
																data-link-area="footer-category" data-link-name="washing_machines">
																<h6>Washing Machines</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/washer-dryers"
																data-link-area="footer-category" data-link-name="washer_dryers">Washer Dryers</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/tumble-dryers"
																data-link-area="footer-category" data-link-name="tumble_dryers">Tumble Dryers</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/styler"
																data-link-area="footer-category" data-link-name="styler">Styler</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/fridge-freezers"
																data-link-area="footer-category" data-link-name="fridge_freezers">
																<h6>Fridge Freezers</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/heating-awhp"
																data-link-area="footer-category" data-link-name="heating_solution_(awhp)">
																<h6>Heating Solution (AWHP)</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a
																href="https://www.lg.com/uk/business/air-conditioning-systems/residential-air-conditioner"
																data-link-area="footer-category"
																data-link-name="residential_air_conditioning">Residential Air Conditioning</a>
														</li>
													</ul>
												</li>
												<li class="link-wrap">
													<div class="footer-title"><a href="https://www.lg.com/uk/computer-products"
															data-link-area="footer-super_category" data-link-name="computer_products">
															<h5>Computer Products</h5>
														</a></div>
													<ul>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/monitors"
																data-link-area="footer-category" data-link-name="monitors">
																<h6>Monitors</h6>
															</a>
														</li>
														<li class="footer-sub-title"><a href="https://www.lg.com/uk/laptops"
																data-link-area="footer-category" data-link-name="laptops">Laptops</a>
														</li>
														<li class="footer-sub-title"><span class="no-link">
																<h6>Buying Guide</h6>
															</span></li>
													</ul>
												</li>
											</ul>
											<ul class="footer-contents-box column-3">
												<li class="footer-contents-inner">
													<ul>
														<li class="link-wrap">
															<div class="footer-title"><a href="https://www.lg.com/uk/support"
																	data-link-area="footer-super_category" data-link-name="support">
																	<h5>Support</h5>
																</a></div>
															<ul>
																<li class="footer-sub-title"><span class="no-link">
																		<h6>Downloads</h6>
																	</span>
																	<ul>
																		<li><a href="https://www.lg.com/uk/support/manuals"
																				data-link-area="footer-sub_category" data-link-name="manuals">Manuals</a></li>
																		<li><a href="https://www.lg.com/uk/support/software-firmware"
																				data-link-area="footer-sub_category"
																				data-link-name="software_&amp;_firmware">Software &amp; Firmware</a></li>
																		<li><a href="https://www.lg.com/uk/support/smart-share"
																				data-link-area="footer-sub_category" data-link-name="smart_share">Smart
																				Share</a></li>
																	</ul>
																</li>
																<li class="footer-sub-title"><span class="no-link">
																		<h6>Guides</h6>
																	</span>
																	<ul>
																		<li><a href="https://www.lg.com/uk/support/product-help"
																				data-link-area="footer-sub_category"
																				data-link-name="searchable_help_articles">Searchable Help Articles</a></li>
																		<li><a href="https://www.lg.com/uk/support/video-tutorials"
																				data-link-area="footer-sub_category" data-link-name="video_tutorials">Video
																				Tutorials</a></li>
																		<li><a href="https://www.lg.com/uk/support/smart-diagnosis"
																				data-link-area="footer-sub_category" data-link-name="smart_diagnosis">Smart
																				Diagnosis</a></li>
																	</ul>
																</li>
																<li class="footer-sub-title"><span class="no-link">
																		<h6>Contact</h6>
																	</span>
																	<ul>
																		<li><a href="https://www.lg.com/uk/support/chat-email"
																				data-link-area="footer-sub_category" data-link-name="chat_&amp;_email">Chat
																				&amp; Email</a></li>
																		<li><a href="https://www.lg.com/uk/support/telephone"
																				data-link-area="footer-sub_category" data-link-name="telephone">Telephone</a>
																		</li>
																		<li><a href="https://www.lg.com/uk/support/inquiry-status"
																				data-link-area="footer-sub_category" data-link-name="inquiry_status">Inquiry
																				Status</a></li>
																		<li><a href="https://www.lg.com/uk/support/web-survey"
																				data-link-area="footer-sub_category" data-link-name="customer_feedback">Customer
																				Feedback</a></li>
																	</ul>
																</li>
																<li class="footer-sub-title"><span class="no-link">
																		<h6>Repair &amp; Warranty</h6>
																	</span>
																	<ul>
																		<li><a href="https://www.lg.com/uk/support/repair-warranty/request-repair"
																				data-link-area="footer-sub_category" data-link-name="request_a_repair">Request a
																				Repair</a></li>
																		<li><a href="https://www.lg.com/uk/support/warranty"
																				data-link-area="footer-sub_category" data-link-name="warranty">Warranty</a></li>
																		<li><a href="https://www.lg.com/uk/support/repair-warranty/business-warranty"
																				data-link-area="footer-sub_category" data-link-name="business_warranty">Business
																				Warranty</a></li>
																	</ul>
																</li>
																<li class="footer-sub-title"><span class="no-link">
																		<h6>Additional Support</h6>
																	</span>
																	<ul>
																		<li><a href="http://www.4lg.co.uk/" data-link-area="footer-sub_category"
																				data-link-name="parts_&amp;_accessories" class="link-text ico-blank"
																				target="_blank" title="Opens in a new window">Parts &amp; Accessories</a></li>
																		<li><a href="https://www.lg.com/uk/support/announcements"
																				data-link-area="footer-sub_category"
																				data-link-name="announcements">Announcements</a></li>
																	</ul>
																</li>
																<li class="footer-sub-title"><a href="https://www.lg.com/uk/support/right-to-repair"
																		data-link-area="footer-category" data-link-name="right_to_repair">Right To
																		Repair</a>
																</li>
																<li class="footer-sub-title"><a href="https://www.lg.com/uk/support/contact/whatsapp"
																		data-link-area="footer-category" data-link-name="support_via_whatsapp">Support via
																		WhatsApp</a>
																</li>
															</ul>
														</li>
													</ul>
												</li>
												<li class="footer-contents-inner">
													<ul>
														<li class="link-wrap">
															<div class="footer-title"><span class="no-link">
																	<h5>LG Online Shop</h5>
																</span></div>
															<ul>
																<li><a href="https://www.lg.com/uk/my-lg/login?page=signup"
																		data-link-area="footer-social_my_account" data-link-name="create_an_account">Create
																		an account</a></li>
																<li><a href="https://www.lg.com/uk/my-lg/my-profilo"
																		data-link-area="footer-social_my_account" data-link-name="my_account">My account</a>
																</li>
																<li><a href="https://www.lg.com/uk/shop/sales/order/history"
																		data-link-area="footer-social_my_account" data-link-name="my_orders">My orders</a>
																</li>
																<li><a href="https://www.lg.com/uk/shop/sales/guest/form"
																		data-link-area="footer-social_my_account"
																		data-link-name="order_status_and_returns">Order Status and Returns</a></li>
																<li><a href="https://www.lg.com/uk/shop/faq" data-link-area="footer-social_my_account"
																		data-link-name="frequently_asked_questions_-_faq">Frequently Asked Questions -
																		FAQ</a></li>
															</ul>
														</li>
														<li class="link-wrap">
															<div class="footer-title"><a href="https://www.lg.com/uk/about-lg"
																	data-link-area="footer-social_my_account" data-link-name="about_lg">
																	<h5>About LG</h5>
																</a></div>
															<ul>
																<li><a href="https://www.lg.com/uk/about-lg/our-brand"
																		data-link-area="footer-social_my_account" data-link-name="our_brand">Our Brand</a>
																</li>
																<li><a href="https://www.lg.com/uk/about-lg/career"
																		data-link-area="footer-social_my_account" data-link-name="careers">Careers</a></li>
																<li><a href="https://www.lg.com/uk/about-lg/press-media"
																		data-link-area="footer-social_my_account" data-link-name="press_&amp;_media">Press
																		&amp; Media</a></li>
																<li><a href="https://www.lg.com/uk/about-lg/sustainability"
																		data-link-area="footer-social_my_account"
																		data-link-name="sustainability">Sustainability</a></li>
															</ul>
														</li>
														<li class="link-wrap">
															<div class="footer-title"><a href="https://www.lg.com/uk/lg-signature"
																	data-link-area="footer-social_my_account" data-link-name="lg_signature">
																	<h5>LG SIGNATURE</h5>
																</a></div>
															<ul>
																<li class="footer-sub-title"><a href="https://www.lg.com/uk/lg-signature"
																		data-link-area="footer-social_my_account" data-link-name="brand_story">Brand
																		Story</a>
																</li>
																<li class="footer-sub-title"><a href="https://www.lg.com/uk/tvs/lg-OLED77W9PLA"
																		data-link-area="footer-social_my_account" data-link-name="lg_signature_oled_tv">LG
																		SIGNATURE OLED TV</a>
																</li>
																<li class="footer-sub-title"><a href="https://www.lg.com/uk/washing-machines/lg-LSF100W"
																		data-link-area="footer-social_my_account"
																		data-link-name="lg_signature_washing_machine">LG SIGNATURE Washing Machine</a>
																</li>
																<li class="footer-sub-title"><a href="https://www.lg.com/uk/fridge-freezers/lg-LSR100"
																		data-link-area="footer-social_my_account"
																		data-link-name="lg_signature_refrigerator">LG SIGNATURE Refrigerator</a>
																</li>
															</ul>
														</li>
														<li class="link-wrap">
															<div class="footer-title"><a href="https://www.lg.com/uk/glossary"
																	data-link-area="footer-social_my_account" data-link-name="glossary">Glossary</a></div>
															<div class="footer-title"><a href="https://www.lg.com/global/support/cedoc/cedoc"
																	data-link-area="footer-social_my_account"
																	data-link-name="compliance_information">Compliance information</a></div>
															<div class="footer-title"><a href="https://www.lg.com/uk/lg-experience"
																	data-link-area="footer-social_my_account" data-link-name="lg_experience">LG
																	EXPERIENCE</a></div>
															<div class="footer-title"><a href="https://www.lg.com/uk/promotions"
																	data-link-area="footer-social_my_account" data-link-name="promotions">Promotions</a>
															</div>
														</li>
													</ul>
												</li>
											</ul>
											<li class="footer-contents-inner">
												<ul></ul>
											</li>
										</div>
									</div> <!-- <div class="footer-box"> -->
									<div class="footer-component">
										<div class="sub-contents social">
											<div class="country-information-wrap">
												<form class="country-information" action="https://www.lg.com/common/index.jsp" method="post"
													target="_blank" title="Opens in a new window"> <input type="hidden" name="countryVal"
														value="EUROPE">
													<div class="icon-wrap"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/country.svg"
															class="earth-icon lazyloade" alt=""
															src="https://www.lg.com/lg5-common/images/common/icons/country.svg" data-loaded="true">
														<div class="icon-tooltip">
															<div class="tooltip-inner">Ireland, United Kingdom</div>
														</div>
													</div><a href="#" data-link-area="footer-country_language" target="_blank"
														title="Opens in a new window" data-link-name="uk_english">UK, English</a>
												</form>
											</div>
											<ul class="social-links">
												<li><a href="https://www.facebook.com/LGUK" target="_blank" title="Opens in a new window"
														class="social-icon icon" data-link-area="footer-social_media_button"
														data-link-name="facebook"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/facebook-circle-fill.svg"
															class="lazyload" alt="Facebook"></a></li>
												<li><a href="https://twitter.com/LGUK" target="_blank" title="Opens in a new window"
														class="social-icon icon" data-link-area="footer-social_media_button"
														data-link-name="twitter"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/twitter-circle-fill.svg"
															class="lazyload" alt="Twitter"></a></li>
												<li><a href="https://www.youtube.com/user/LGBlogUK" target="_blank"
														title="Opens in a new window" class="social-icon icon"
														data-link-area="footer-social_media_button" data-link-name="youtube"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/youtube-circle-fill.svg"
															class="lazyload" alt="Youtube"></a></li>
												<li><a href="http://www.instagram.com/lg_uk" target="_blank" title="Opens in a new window"
														class="social-icon icon" data-link-area="footer-social_media_button"
														data-link-name="instagram"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/instagram-circle-fill.svg"
															class="lazyload" alt="Instagram"></a></li>
											</ul>
										</div>
									</div>
									<div class="footer-bottom-box" id="lgSkipToSitemap">
										<div class="footer-bottom">
											<div class="footer-component">
												<div class="bottom-links">
													<div class="links-left">
														<ul>
															<li><a href="https://www.lg.com/uk/business" data-link-area="footer-legal_sitemap"
																	data-link-name="for_business">For Business</a></li>
															<li><a href="https://www.lg.com/uk/sitemap" data-link-area="footer-legal_sitemap"
																	data-link-name="site_map">Site Map</a></li>
															<li><a href="https://www.lg.com/uk/privacy" data-link-area="footer-legal_sitemap"
																	data-link-name="privacy">Privacy Policy</a></li>
															<li><a href="#" data-link-area="footer-legal_sitemap" data-link-name="cookie">Cookie</a>
															</li>
															<li><a href="https://www.lg.com/uk/legal" data-link-area="footer-legal_sitemap"
																	data-link-name="legal">Legal</a></li>
															<li><a href="https://www.lg.com/uk/webaccessibility" data-link-area="footer-legal_sitemap"
																	data-link-name="accessibility_help" id="lgAccHelp">Accessibility Help</a></li>
														</ul>
														<div class="copyright"> Copyright © 2009-2022 LG Electronics. All Rights Reserved <a
																href="http://www.lgcorp.com/about/companies" target="_blank"
																title="Opens in a new window" class="description"> This is LG Electronics' official
																homepage. If you want to connect to LG Corp., or other LG affiliates, please click </a>
														</div>
													</div>
													<div class="links-right"> <a href="https://www.lg.com/uk/support/slavery-act-statement"
															class="uk_link1" target="_blank" title="Opens in a new window">UK Slavery Act
															Statement</a> <a href="//ethics.lg.co.kr/main/en.do"
															data-link-area="footer-jeongdo_management" data-link-name="" target="_blank"
															title="Opens in a new window" class="link-text bold ico-right">LG Jeong-Do Management
															Ethics Hotline</a> </div>
												</div>
											</div>
										</div>
									</div>
								</div>
								<div class="visible-mobile">
									<div class="skip_nav"> <a href="#lgSkipToSitemapMobile" data-link-area="footer-skip_to_sitemap"
											data-link-name="">Skip to Sitemap</a> </div>
									<div class="footer-component">
										<div class="footer-contents">
											<div class="footer-contents-box">
												<div class="box-wrap">
													<div class="footer-title"><span class="no-link">Phone Support</span></div>
													<div class="support-text"><span>Consumer Support</span><span>Monday to Friday, 9:00am to
															5:00pm</span><span>Saturday, 9:00am to 3:00pm </span><span>Closed: Sunday and Bank
															Holidays</span><span><a href="tel:03448475454" style="text-decoration:none">UK : 0344 847
																5454</a></span><span>IE : 01 686 9454</span></div>
													<div class="support-text"><span>Commercial Support</span><span>Exclusively for Air
															Conditioning and Heating</span><span><a href="tel:08448471402"
																style="text-decoration:none">UK : 08448 471 402</a>option 4</span><span><a
																href="tel:0919274459" style="text-decoration:none">Ireland : 0919 274 459</a></span>
													</div>
												</div>
												<div class="box-wrap">
													<div class="footer-title"><a href="https://www.lg.com/uk/support/chat-email"
															data-link-area="footer-chat_&amp;_email" data-link-name="chat_&amp;_email">Email
															Support</a></div>
												</div>
											</div>
											<div class="footer-contents-box site-list">
												<div class="link-wrap">
													<span class="depth-1 has-category depth-category"><a href="#"><span>Products</span></a></span>
													<div class="depth-2">
														<div class="category-block">
															<span class="depth-category has-category"><a href="https://www.lg.com/uk/tv-audio-video"
																	aria-expanded="false" role="button" data-link-area="footer-super_category"
																	data-link-name="tv/audio/video"
																	class="category-button"><span>TV/Audio/Video</span></a></span>
															<div class="depth-2-list in-depth">
																<ul>
																	<li><a href="https://www.lg.com/uk/tvs" data-link-area="footer-category"
																			data-link-name="tvs"><span>TVs</span></a></li>
																	<li><a href="https://www.lg.com/uk/speakers-sound-systems"
																			data-link-area="footer-category"
																			data-link-name="speakers_&amp;_sound_systems"><span>Speakers &amp; Sound
																				Systems</span></a></li>
																	<li><a href="https://www.lg.com/uk/blu-ray-dvd-players"
																			data-link-area="footer-category"
																			data-link-name="blu-ray-dvd_players"><span>Blu-ray &amp; DVD Players</span></a>
																	</li>
																	<li><a href="https://www.lg.com/uk/projectors" data-link-area="footer-category"
																			data-link-name="projectors"><span>PROJECTORS</span></a></li>
																	<li><a href="https://www.lg.com/uk/home-cinema-systems"
																			data-link-area="footer-category" data-link-name="home_cinema_systems"><span>Home
																				Cinema Systems</span></a></li>
																	<li><a href="https://www.lg.com/uk/true-wireless-earbuds"
																			data-link-area="footer-category" data-link-name="true_wireless_earbuds"><span>True
																				Wireless Earbuds</span></a></li>
																	<li><a href="https://www.lg.com/uk/tv-accessories" data-link-area="footer-category"
																			data-link-name="tv_accessories"><span>TV Accessories</span></a></li>
																	<li><a href="https://gb.lgappstv.com/main?lang=eng_GB"
																			data-link-area="footer-category" data-link-name="lg_content_store(tv)"
																			class="link-text ico-blank" target="_blank" title="Opens in a new window"><span>LG
																				Content Store(TV)</span></a></li>
																	<li><span class="no-link"><span>Buying Guide</span></span></li>
																</ul>
															</div>
														</div>
														<div class="category-block">
															<span class="depth-category has-category"><a href="https://www.lg.com/uk/appliances"
																	aria-expanded="false" role="button" data-link-area="footer-super_category"
																	data-link-name="appliances" class="category-button"><span>Appliances</span></a></span>
															<div class="depth-2-list in-depth">
																<ul>
																	<li><a href="https://www.lg.com/uk/washing-machines" data-link-area="footer-category"
																			data-link-name="washing_machines"><span>Washing Machines</span></a></li>
																	<li><a href="https://www.lg.com/uk/washer-dryers" data-link-area="footer-category"
																			data-link-name="washer_dryers"><span>Washer Dryers</span></a></li>
																	<li><a href="https://www.lg.com/uk/tumble-dryers" data-link-area="footer-category"
																			data-link-name="tumble_dryers"><span>Tumble Dryers</span></a></li>
																	<li><a href="https://www.lg.com/uk/styler" data-link-area="footer-category"
																			data-link-name="styler"><span>Styler</span></a></li>
																	<li><a href="https://www.lg.com/uk/fridge-freezers" data-link-area="footer-category"
																			data-link-name="fridge_freezers"><span>Fridge Freezers</span></a></li>
																	<li><a href="https://www.lg.com/uk/heating-awhp" data-link-area="footer-category"
																			data-link-name="heating_solution_(awhp)"><span>Heating Solution (AWHP)</span></a>
																	</li>
																	<li><a
																			href="https://www.lg.com/uk/business/air-conditioning-systems/residential-air-conditioner"
																			data-link-area="footer-category"
																			data-link-name="residential_air_conditioning"><span>Residential Air
																				Conditioning</span></a></li>
																</ul>
															</div>
														</div>
														<div class="category-block">
															<span class="depth-category has-category"><a
																	href="https://www.lg.com/uk/computer-products" aria-expanded="false" role="button"
																	data-link-area="footer-super_category" data-link-name="computer_products"
																	class="category-button"><span>Computer Products</span></a></span>
															<div class="depth-2-list in-depth">
																<ul>
																	<li><a href="https://www.lg.com/uk/monitors" data-link-area="footer-category"
																			data-link-name="monitors"><span>Monitors</span></a></li>
																	<li><a href="https://www.lg.com/uk/laptops" data-link-area="footer-category"
																			data-link-name="laptops"><span>Laptops</span></a></li>
																	<li><span class="no-link"><span>Buying Guide</span></span></li>
																</ul>
															</div>
														</div>
													</div>
												</div>
												<div class="link-wrap">
													<span class="depth-1 has-category depth-category"><a href="https://www.lg.com/uk/support"
															data-link-area="footer-super_category" data-link-name="support" aria-expanded="false"
															role="button"><span>Support</span></a></span>
													<div class="depth-2-list in-depth">
														<ul>
															<li class="depth-title"><span class="no-link"><span>Downloads</span></span></li>
															<li><a href="https://www.lg.com/uk/support/manuals" data-link-area="footer-sub_category"
																	data-link-name="manuals">Manuals</a></li>
															<li><a href="https://www.lg.com/uk/support/software-firmware"
																	data-link-area="footer-sub_category" data-link-name="software_&amp;_firmware">Software
																	&amp; Firmware</a></li>
															<li><a href="https://www.lg.com/uk/support/smart-share"
																	data-link-area="footer-sub_category" data-link-name="smart_share">Smart Share</a></li>
															<li class="depth-title"><span class="no-link"><span>Guides</span></span></li>
															<li><a href="https://www.lg.com/uk/support/product-help"
																	data-link-area="footer-sub_category"
																	data-link-name="searchable_help_articles">Searchable Help Articles</a></li>
															<li><a href="https://www.lg.com/uk/support/video-tutorials"
																	data-link-area="footer-sub_category" data-link-name="video_tutorials">Video
																	Tutorials</a></li>
															<li><a href="https://www.lg.com/uk/support/smart-diagnosis"
																	data-link-area="footer-sub_category" data-link-name="smart_diagnosis">Smart
																	Diagnosis</a></li>
															<li class="depth-title"><span class="no-link"><span>Contact</span></span></li>
															<li><a href="https://www.lg.com/uk/support/chat-email"
																	data-link-area="footer-sub_category" data-link-name="chat_&amp;_email">Chat &amp;
																	Email</a></li>
															<li><a href="https://www.lg.com/uk/support/telephone" data-link-area="footer-sub_category"
																	data-link-name="telephone">Telephone</a></li>
															<li><a href="https://www.lg.com/uk/support/inquiry-status"
																	data-link-area="footer-sub_category" data-link-name="inquiry_status">Inquiry
																	Status</a></li>
															<li><a href="https://www.lg.com/uk/support/web-survey"
																	data-link-area="footer-sub_category" data-link-name="customer_feedback">Customer
																	Feedback</a></li>
															<li class="depth-title"><span class="no-link"><span>Repair &amp; Warranty</span></span>
															</li>
															<li><a href="https://www.lg.com/uk/support/repair-warranty/request-repair"
																	data-link-area="footer-sub_category" data-link-name="request_a_repair">Request a
																	Repair</a></li>
															<li><a href="https://www.lg.com/uk/support/warranty" data-link-area="footer-sub_category"
																	data-link-name="warranty">Warranty</a></li>
															<li><a href="https://www.lg.com/uk/support/repair-warranty/business-warranty"
																	data-link-area="footer-sub_category" data-link-name="business_warranty">Business
																	Warranty</a></li>
															<li class="depth-title"><span class="no-link"><span>Additional Support</span></span></li>
															<li><a href="http://www.4lg.co.uk/" data-link-area="footer-sub_category"
																	data-link-name="parts_&amp;_accessories" class="link-text ico-blank" target="_blank"
																	title="Opens in a new window">Parts &amp; Accessories</a></li>
															<li><a href="https://www.lg.com/uk/support/announcements"
																	data-link-area="footer-sub_category" data-link-name="announcements">Announcements</a>
															</li>
															<li class="depth-title"><a href="https://www.lg.com/uk/support/right-to-repair"
																	data-link-area="footer-category" data-link-name="right_to_repair"><span>Right To
																		Repair</span></a></li>
															<li class="depth-title"><a href="https://www.lg.com/uk/support/contact/whatsapp"
																	data-link-area="footer-category" data-link-name="support_via_whatsapp"><span>Support
																		via WhatsApp</span></a></li>
														</ul>
													</div>
												</div>
												<div class="link-wrap">
													<span class="depth-1 has-category depth-category"><a href="#none" class="no-link"
															data-link-area="footer-social_my_account" data-link-name="lg_online_shop"><span>LG Online
																Shop</span></a></span>
													<div class="depth-2-list in-depth">
														<ul>
															<li><a href="https://www.lg.com/uk/my-lg/login?page=signup"
																	data-link-area="footer-social_my_account" data-link-name="create_an_account">Create an
																	account</a></li>
															<li><a href="https://www.lg.com/uk/my-lg/my-profilo"
																	data-link-area="footer-social_my_account" data-link-name="my_account">My account</a>
															</li>
															<li><a href="https://www.lg.com/uk/shop/sales/order/history"
																	data-link-area="footer-social_my_account" data-link-name="my_orders">My orders</a>
															</li>
															<li><a href="https://www.lg.com/uk/shop/sales/guest/form"
																	data-link-area="footer-social_my_account"
																	data-link-name="order_status_and_returns">Order Status and Returns</a></li>
															<li><a href="https://www.lg.com/uk/shop/faq" data-link-area="footer-social_my_account"
																	data-link-name="frequently_asked_questions_-_faq">Frequently Asked Questions - FAQ</a>
															</li>
														</ul>
													</div>
												</div>
												<div class="link-wrap">
													<span class="depth-1 has-category depth-category"><a href="https://www.lg.com/uk/about-lg"
															aria-expanded="false" role="button" data-link-area="footer-social_my_account"
															data-link-name="about_lg" class="category-button"><span>About LG</span></a></span>
													<div class="depth-2-list in-depth">
														<ul>
															<li><a href="https://www.lg.com/uk/about-lg/our-brand"
																	data-link-area="footer-social_my_account" data-link-name="our_brand">Our Brand</a>
															</li>
															<li><a href="https://www.lg.com/uk/about-lg/career"
																	data-link-area="footer-social_my_account" data-link-name="careers">Careers</a></li>
															<li><a href="https://www.lg.com/uk/about-lg/press-media"
																	data-link-area="footer-social_my_account" data-link-name="press_&amp;_media">Press
																	&amp; Media</a></li>
															<li><a href="https://www.lg.com/uk/about-lg/sustainability"
																	data-link-area="footer-social_my_account"
																	data-link-name="sustainability">Sustainability</a></li>
														</ul>
													</div>
												</div>
												<div class="link-wrap">
													<span class="depth-1 has-category depth-category"><a href="https://www.lg.com/uk/lg-signature"
															aria-expanded="false" role="button" data-link-area="footer-social_my_account"
															data-link-name="lg_signature" class="category-button"><span>LG SIGNATURE</span></a></span>
													<div class="depth-2-list in-depth">
														<ul>
															<li class="depth-title"><a href="https://www.lg.com/uk/lg-signature"
																	data-link-area="footer-social_my_account" data-link-name="brand_story"><span>Brand
																		Story</span></a></li>
															<li class="depth-title"><a href="https://www.lg.com/uk/tvs/lg-OLED77W9PLA"
																	data-link-area="footer-social_my_account"
																	data-link-name="lg_signature_oled_tv"><span>LG SIGNATURE OLED TV</span></a></li>
															<li class="depth-title"><a href="https://www.lg.com/uk/washing-machines/lg-LSF100W"
																	data-link-area="footer-social_my_account"
																	data-link-name="lg_signature_washing_machine"><span>LG SIGNATURE Washing
																		Machine</span></a></li>
															<li class="depth-title"><a href="https://www.lg.com/uk/fridge-freezers/lg-LSR100"
																	data-link-area="footer-social_my_account"
																	data-link-name="lg_signature_refrigerator"><span>LG SIGNATURE Refrigerator</span></a>
															</li>
														</ul>
													</div>
												</div>
												<div class="link-wrap">
													<span class="depth-1 depth-category"><a href="https://www.lg.com/uk/glossary"
															aria-expanded="false" role="button" data-link-area="footer-social_my_account"
															data-link-name="glossary" class="category-button"><span>Glossary</span></a></span>
												</div>
												<div class="link-wrap">
													<span class="depth-1 depth-category"><a href="https://www.lg.com/global/support/cedoc/cedoc"
															aria-expanded="false" role="button" data-link-area="footer-social_my_account"
															data-link-name="compliance_information" class="category-button"><span>Compliance
																information</span></a></span>
												</div>
												<div class="link-wrap">
													<span class="depth-1 depth-category"><a href="https://www.lg.com/uk/lg-experience"
															aria-expanded="false" role="button" data-link-area="footer-social_my_account"
															data-link-name="lg_experience" class="category-button"><span>LG
																EXPERIENCE</span></a></span>
												</div>
												<div class="link-wrap">
													<span class="depth-1 depth-category"><a href="https://www.lg.com/uk/promotions"
															aria-expanded="false" role="button" data-link-area="footer-social_my_account"
															data-link-name="promotions" class="category-button"><span>Promotions</span></a></span>
												</div>
											</div>
										</div>
									</div> <!-- <div class="footer-box"> -->
									<div class="footer-component">
										<div class="sub-contents social">
											<div class="country-information-wrap">
												<form class="country-information" action="https://www.lg.com/common/index.jsp" method="post"
													target="_blank" title="Opens in a new window"> <input type="hidden" name="countryVal"
														value="EUROPE">
													<div class="icon-wrap"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/country.svg"
															class="earth-icon lazyloade" alt=""
															src="https://www.lg.com/lg5-common/images/common/icons/country.svg" data-loaded="true">
														<div class="icon-tooltip">
															<div class="tooltip-inner">Ireland, United Kingdom</div>
														</div>
													</div><a href="#" data-link-area="footer-country_language" target="_blank"
														title="Opens in a new window" data-link-name="uk_english">UK, English</a>
												</form>
											</div>
											<ul class="social-links">
												<li><a href="https://www.facebook.com/LGUK" target="_blank" title="Opens in a new window"
														class="social-icon icon" data-link-area="footer-social_media_button"
														data-link-name="facebook"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/facebook-circle-fill.svg"
															class="lazyload" alt="Facebook"></a></li>
												<li><a href="https://twitter.com/LGUK" target="_blank" title="Opens in a new window"
														class="social-icon icon" data-link-area="footer-social_media_button"
														data-link-name="twitter"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/twitter-circle-fill.svg"
															class="lazyload" alt="Twitter"></a></li>
												<li><a href="https://www.youtube.com/user/LGBlogUK" target="_blank"
														title="Opens in a new window" class="social-icon icon"
														data-link-area="footer-social_media_button" data-link-name="youtube"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/youtube-circle-fill.svg"
															class="lazyload" alt="Youtube"></a></li>
												<li><a href="http://www.instagram.com/lg_uk" target="_blank" title="Opens in a new window"
														class="social-icon icon" data-link-area="footer-social_media_button"
														data-link-name="instagram"><img
															data-src="https://www.lg.com/lg5-common/images/common/icons/instagram-circle-fill.svg"
															class="lazyload" alt="Instagram"></a></li>
											</ul>
										</div>
									</div>
									<div class="footer-bottom-box" id="lgSkipToSitemapMobile">
										<div class="footer-bottom">
											<div class="footer-component">
												<div class="bottom-links">
													<div class="links-box">
														<ul>
															<li><a href="https://www.lg.com/uk/business" data-link-area="footer-legal_sitemap"
																	data-link-name="for_business">For Business</a></li>
															<li><a href="https://www.lg.com/uk/sitemap" data-link-area="footer-legal_sitemap"
																	data-link-name="site_map">Site Map</a></li>
															<li><a href="https://www.lg.com/uk/privacy" data-link-area="footer-legal_sitemap"
																	data-link-name="privacy">Privacy Policy</a></li>
															<li><a href="#" data-link-area="footer-legal_sitemap" data-link-name="cookie">Cookie</a>
															</li>
															<li><a href="https://www.lg.com/uk/legal" data-link-area="footer-legal_sitemap"
																	data-link-name="legal">Legal</a></li>
															<li><a href="https://www.lg.com/uk/webaccessibility" data-link-area="footer-legal_sitemap"
																	data-link-name="accessibility_help">Accessibility Help</a></li>
														</ul>
													</div>
												</div>
												<div class="copyright"> Copyright © 2009-2022 LG Electronics. All Rights Reserved <div
														class="description"> <a href="http://www.lgcorp.com/about/companies" target="_blank"
															title="Opens in a new window" class="description"> This is LG Electronics' official
															homepage. If you want to connect to LG Corp., or other LG affiliates, please click </a>
													</div>
												</div>
											</div>
											<div class="links-bottom">
												<div class="links-wrap"> <a href="https://www.lg.com/uk/support/slavery-act-statement"
														class="uk_link1" target="_blank" title="Opens in a new window">UK Slavery Act Statement</a>
													<a href="http://ethics.lg.co.kr/main/en.do" data-link-area="footer-jeongdo_management"
														data-link-name="" target="_blank" title="Opens in a new window"
														class="link-text bold ico-right">LG Jeong-Do Management Ethics Hotline</a> </div>
											</div>
										</div>
									</div>
								</div>
								<div class="modal modal-simple modal-cookie-setting" id="modal_cookie_set" tabindex="-1" role="dialog"
									data-backdrop="false">
									<div class="modal-dialog" role="document">
										<div class="modal-content">
											<div class="modal-body">
												<div class="first-section">
													<h2 class="m-title">LG.COM COOKIES</h2>
													<p class="m-desc">We use cookies, including cookies from third parties, to enhance your user
														experience and the effectiveness of our marketing activities. These cookies are performance,
														analytics and advertising cookies, please see our <a href="/uk/privacy"
															class="link-carmine">Privacy and Cookie policy</a> for further information. If you agree
														to all of our cookies select “Accept all ” or select “Cookie Settings” to see which cookies
														we use and choose which ones you would like to accept.</p>
													<div class="btn-area"><button type="button"
															class="btn btn-primary btn-sm toggle-setting-area closed">Cookie Settings</button><button
															type="button" class="btn btn-primary btn-sm accept-all">Accept All</button></div>
												</div>
												<div class="sec-section">
													<ul>
														<li class="detail-option-key LGCOM_ADVERTISING">
															<dl>
																<dt>Advertising Cookies</dt>
																<dd>
																	<div class="toggle-active-button" data-active-text="active"
																		data-disactive-text="disactive"><button type="button"><span
																				class="sr-only">active</span></button></div>
																	<div class="toggle-open-button" data-open-text="open" data-close-text="close"><button
																			type="button"><span class="sr-only">open</span></button></div>
																	<p>These cookies enable us to show you ads and other content that we think is most
																		attuned to your interests and digital behavior.</p>
																</dd>
															</dl>
														</li>
														<li class="detail-option-key LGCOM_ANALYSIS_OF_SITE">
															<dl>
																<dt>Analytics Cookies</dt>
																<dd>
																	<div class="toggle-active-button" data-active-text="active"
																		data-disactive-text="disactive"><button type="button"><span
																				class="sr-only">active</span></button></div>
																	<div class="toggle-open-button" data-open-text="open" data-close-text="close"><button
																			type="button"><span class="sr-only">open</span></button></div>
																	<p>These cookies allow our website to keep improving functions through website traffic
																		analysis and to suggest personalized content for you.</p>
																</dd>
															</dl>
														</li>
														<li class="detail-option-key LGCOM_IMPROVEMENTS">
															<dl>
																<dt>Functional Cookies</dt>
																<dd>
																	<div class="toggle-active-button" data-active-text="active"
																		data-disactive-text="disactive"><button type="button"><span
																				class="sr-only">active</span></button></div>
																	<div class="toggle-open-button" data-open-text="open" data-close-text="close"><button
																			type="button"><span class="sr-only">open</span></button></div>
																	<p>These cookies are used to provide you with convenient functions, such as product
																		reviews and product video playback, during your web browsing, they also enable
																		interaction with social media accounts.</p>
																</dd>
															</dl>
														</li>
													</ul>
													<div class="bottom-text submit"><button type="button">SAVE &amp; PROCEED</button></div>
												</div>
											</div>
										</div>
									</div>
								</div>
							</footer>
						</div>
						<!-- <input type="hidden" id="kinesisorigin" value="PROD"><input type="hidden" id="kinesislocale" value="UK"> -->
						<!-- <script src="https://www.lg.com/lg5-common/library/aws-sdk-kinesis-2.617.0.min.min.js"></script>
						<script src="https://www.lg.com/lg5-common-gp/js/gp-kinesis-webdata.min.js"></script> -->

					</div>
				</div>
			</div>
		</div>