<div class="container-fluid iw_section" id="sectionjrfoy4w3">
			<div class="row iw_row iw_stretch" id="rowjrfoy4w4">
				<div class="iw_columns col-lg-12" id="coljrfoy4w5">
					<div class="iw_component" id="iw_comp1548641136962">

						<div class="broswe-check-popup-layer" id="modal_browse_supported_guide" tabindex="-1" role="dialog">
							<div class="modal-background" id="modal-background"></div>
							<div class="modal-contents" role="document">
								<div class="modal-contentainer">
									<div class="modal-header">
										<strong class="modal-title"><img src="/lg5-common/images/common/logo-modal-head.jpg"
												alt="LG"></strong>
										<button type="button" class="modal-layer-close" id="modal-layer-close"><img
												src="/lg5-common/images/common/popup-close.png" alt="Close"></button>
									</div>
									<div class="modal-body">

										<div class="browse-supported-guide">
											<div class="headbox">
												To properly experience our LG.com website, you will need to use an alternate browser or upgrade
												to a newer version of internet Explorer (IE10 or greater).
											</div>
											<div class="guide-paragraph">
												The LG.com website utilizes responsive design to provide convenient experience that conforms to
												your devices screen size. In order to get the best possible experience our LG.COM website please
												follow below instructions. If you’re using Internet Explorer 9 or earlier, you will need to use
												an alternate browser such as Firefox or Chrome or upgrade to a newer version of internet
												Explorer (IE10 or greater).
											</div>
										</div>

									</div>
								</div>
							</div>
						</div>
						<div>
							<div role="presentation" class="cookie-eu-get-height"></div>
							<div class="cookie-banner eprivacy-cookie cookie-eu row" id="eprivacyCookie" role="banner"
								data-privacy-type="static" data-cookie-list="https://www.lg.com/uk/mkt/ajax/retrieveEprivacyCookie">
								<div class="default"> <button type="button" class="open-button">Change your Cookie Setting</button>
								</div>
								<div class="open">
									<div class="inner">
										<div class="full">
											<p class="cookie-title">LG.COM COOKIES</p>
											<p> We use cookies, including cookies from third parties, to enhance your user experience and the
												effectiveness of our marketing activities. These cookies are performance, analytics and
												advertising cookies, please see our <a href="/uk/privacy" class="link-carmine">Privacy and
													Cookie policy</a> for further information. If you agree to all of our cookies select “Accept
												all ” or select “Cookie Settings” to see which cookies we use and choose which ones you would
												like to accept. </p>
										</div>
										<div class="btn-area"> <button type="button"
												class="btn btn-primary btn-sm toggle-setting-area closed">Cookie Settings</button> <button
												type="button" class="btn btn-primary btn-sm accept-all">Accept All</button> </div>
									</div>
								</div>
								<div class="more">
									<div class="inner">
										<ul>
											<li class="detail-option-key LGCOM_NECESSARY hidden">
												<dl>
													<dt>eprivacy_explicit_NECESSARY_title</dt>
													<dd>
														<div class="toggle-open-button" data-open-text="open" data-close-text="close"> <button
																type="button"><span class="sr-only">open</span></button> </div>
														<div class="toggle-active-button" data-active-text="active" data-disactive-text="disactive">
															<button type="button" class="active"><span class="sr-only">active</span></button> </div>
														<p>eprivacy_explicit_NECESSARY_desc</p>
													</dd>
												</dl>
											</li>
											<li class="detail-option-key LGCOM_IMPROVEMENTS">
												<dl>
													<dt>Functional Cookies</dt>
													<dd>
														<div class="toggle-open-button" data-open-text="open" data-close-text="close"> <button
																type="button"><span class="sr-only">open</span></button> </div>
														<div class="toggle-active-button" data-active-text="active" data-disactive-text="disactive">
															<button type="button"><span class="sr-only">disactive</span></button> </div>
														<p>These cookies are used to provide you with convenient functions, such as product reviews
															and product video playback, during your web browsing, they also enable interaction with
															social media accounts.</p>
													</dd>
												</dl>
											</li>
											<li class="detail-option-key LGCOM_ANALYSIS_OF_SITE">
												<dl>
													<dt>Analytics Cookies</dt>
													<dd>
														<div class="toggle-open-button" data-open-text="open" data-close-text="close"> <button
																type="button"><span class="sr-only">open</span></button> </div>
														<div class="toggle-active-button" data-active-text="active" data-disactive-text="disactive">
															<button type="button"><span class="sr-only">disactive</span></button> </div>
														<p>These cookies allow our website to keep improving functions through website traffic
															analysis and to suggest personalized content for you.</p>
													</dd>
												</dl>
											</li>
											<li class="detail-option-key LGCOM_ADVERTISING">
												<dl>
													<dt>Advertising Cookies</dt>
													<dd>
														<div class="toggle-open-button" data-open-text="open" data-close-text="close"> <button
																type="button"><span class="sr-only">open</span></button> </div>
														<div class="toggle-active-button" data-active-text="active" data-disactive-text="disactive">
															<button type="button"><span class="sr-only">disactive</span></button> </div>
														<p>These cookies enable us to show you ads and other content that we think is most attuned
															to your interests and digital behavior.</p>
													</dd>
												</dl>
											</li>
										</ul>
										<div class="bottom-text submit"> <button type="button" class="save-submit">SAVE &amp;
												PROCEED</button> </div>
									</div>
								</div> <template>
									<div class="cookie-permit-msg small"> <img
											data-src="https://www.lg.com/lg5-common-gp/images/common/icons/no-contents.svg"
											class="info-icon lazyload" alt=""
											src="https://www.lg.com/lg5-common-gp/images/common/icons/no-contents.svg" data-loaded="true">
										<div class="info-text">
											<p>This function is disabled on your cookie management. </p>
											<p>To activate it, click on the link <a href="#">"Edit cookie settings"</a> in the upper </p>
											<p>right corner of this page.</p>
										</div>
									</div>
									<div class="eprivacy-layer">
										<div class="eprivacy-message-wrap above center">
											<div class="eprivacy-message-inner">
												<div class="title">Change your Cookie Setting</div>
												<div class="description"> This function is disabled on your cookie management. To activate it,
													click on the link <a href="#">"Edit cookie settings"</a> in the upper right corner of this
													page. </div>
												<div class="btn-cover"> <button type="button" role-description="layer close button"><span
															class="sr-only">close</span></button> </div>
											</div>
										</div>
									</div>
								</template>
							</div>
							<div class="skip_nav row"> <a href="#content" data-link-area="gnb-skip_to_contents" data-link-name="">Skip
									to Contents</a> <a href="#lgAccHelp">Skip to Accessibility Help</a></div>
							<header class="navigation b2c" data-login-check="https://www.lg.com/uk/mkt/ajax/commonmodule/loginInfo"
								data-cart-check="https://www.lg.com/uk/shop/graphql" data-store="uk" data-obs="Y"
								data-previous="Previous" data-next="Next" data-close-video="Close Video"
								data-fbq-url="https://www.lg.com/uk/mkt/ajax/retrieveEprivacyCookie" data-obs-referrer-flag="N">
								<div class="row for-desktop">
									<div class="size">
										<div class="logo"> <a href="https://www.lg.com/uk" data-link-area="gnb_brand_identity"
												data-link-name=""><img src="https://www.lg.com/lg5-common-gp/images/common/header/logo-b2c.jpg"
													alt="LG Life's good"></a> </div>
										<nav class="links">
											<div class="navi-top">
												<div class="left-top"><a href="https://www.lg.com/uk/lg-signature"
														data-link-area="gnb-lg_brand_logo" data-link-name="lg_signature"><img
															src="https://www.lg.com/uk/images/gnb-global/lg-signature-logo.png" alt=""></a>
												</div>
												<div class="right-top"><a href="https://www.lg.com/uk/business"
														data-link-area="gnb-business_toggle" data-link-name="business">Business</a></div>
											</div>
											<div class="navi-btm">
												<div class="left-btm" itemscope itemtype="http://www.schema.org/SiteNavigationElement">
													<ul class="depth1">
														<li class="depth1-holder">
															<a href="#" data-link-area="gnb-b2c_primary_navigation_items"
																data-link-name="products"><span>Products</span></a>
															<div class="scroll">
																<div class="scroll-left"><a href="#"><span class="sr-only">Previous</span></a></div>
																<ul class="depth2">
																	<li><a href="https://www.lg.com/uk/tv-audio-video" data-id="gnbNV00012003"
																			data-link-area="gnb-b2c_primary_navigation_items"
																			data-link-name="tv/audio/video"><span>TV/Audio/Video</span></a>
																		<div class="sublayer" id="gnbNV00012003">
																			<div class="skip_nav"><a href="#" role="button">Skip to Next Menu</a></div>
																			<div class="sublayer-inner">
																				<div class="columns">
																					<div class="column">
																						<div class="head-link" itemprop="name"><a
																								href="https://www.lg.com/uk/tv-audio-video" itemprop="url"
																								data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																								data-link-name="tv/audio/video">TV/Audio/Video</a></div>
																						<ul>
																							<li class="sub-link"><a href="https://www.lg.com/uk/tvs"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="tvs">TVs</a>
																								<ul class="link-list">
																									<li class="link"><a
																											href="https://www.lg.com/global/lg-signature/rollable-oled-tv-r"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="rollable_oled_tv" target="_blank"
																											title="Opens in a new window">Rollable OLED TV</a></li>
																									<li class="link"><a href="https://www.lg.com/uk/oled-tvs"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="oled_tvs">OLED TVs</a></li>
																									<li class="link"><a href="https://www.lg.com/uk/qned-tvs"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="qned_miniled_tvs">QNED MiniLED TVs</a></li>
																									<li class="link"><a href="https://www.lg.com/uk/nanocell-tvs"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="nanocell_tvs">NanoCell TVs</a></li>
																									<li class="link"><a href="https://www.lg.com/uk/ultra-large-tvs"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="ultra_large_tvs">Ultra Large TVs</a></li>
																									<li class="link"><a href="https://www.lg.com/uk/ultra-hd-4k-tvs"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="uhd_4k_tvs">UHD 4K TVs</a></li>
																									<li class="link"><a href="https://www.lg.com/uk/smart-tvs"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="smart_tvs">Smart TVs</a></li>
																									<li class="link"><a href="https://www.lg.com/uk/led-tvs"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="led_tvs">LED TVs</a></li>
																								</ul>
																							</li>
																							<li class="sub-link"><a
																									href="https://www.lg.com/uk/speakers-sound-systems"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="speakers_&amp;_sound_systems">Speakers &amp; Sound
																									Systems</a>
																								<ul class="link-list">
																									<li class="link"><a href="https://www.lg.com/uk/gaming-speakers"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="gaming-speakers">Gaming Speakers</a></li>
																								</ul>
																							</li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/true-wireless-earbuds"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="true_wireless_earbuds">True Wireless Earbuds</a>
																								<ul class="link-list">
																									<li class="link"><a
																											href="https://www.lg.com/uk/bacteria-killing-earbuds"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="bacteria-killing_earbuds">Bacteria-killing
																											Earbuds</a></li>
																									<li class="link"><a
																											href="https://www.lg.com/uk/active-noise-cancelling-earbuds"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="active_noise_cancelling_earbuds">Active Noise
																											Cancelling Earbuds</a></li>
																								</ul>
																							</li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/blu-ray-dvd-players"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="blu-ray-dvd_players">Blu-ray &amp; DVD Players</a>
																							</li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/projectors"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="projectors">PROJECTORS</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/home-cinema-systems"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="home_cinema_systems">Home Cinema Systems</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/tv-accessories"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="tv_accessories">TV Accessories</a></li>
																						</ul>
																					</div>
																					<div class="column">
																						<ul>
																							<li class="sub-link"><span class="no-link">Buying Guide</span>
																								<ul class="link-list">
																									<li class="link"><a
																											href="https://www.lg.com/uk/projector-buying-guide"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="projector">Projector</a></li>
																								</ul>
																							</li>
																						</ul>
																					</div>
																					<div class="column banner">
																						<a href="https://www.lg.com/uk/true-wireless-earbuds/2021/tonefree"
																							data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner"
																							data-link-name="lg-tone-ufp9" class="white">
																							<div class="banner-visual outside">
																								<img
																									data-src="https://www.lg.com/uk/images/gnb-global/LG_TONEFree_UFP9_GNB_UK.jpg"
																									class="lazyload" alt="">
																								<div class="banner-description bottom">
																									<div class="banner-desc"></div>
																									<div class="banner-head"></div>
																									<div class="banner-link">
																										<span>Find Out More</span>
																									</div>
																								</div>
																							</div>
																						</a>
																					</div>
																					<div class="column featured-product">
																						<div class="gnb-feature">
																							<div class="feature-box"
																								data-wa-msg="Main Product ##1 in TV/Audio/Video Category ">
																								<div class="item">
																									<a href="https://www.lg.com/uk/tvs/lg-oled88z19la"
																										data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																										data-link-name="LG SIGNATURE OLED 8K TV,">
																										<div class="image">
																											<img
																												data-src="https://www.lg.com/uk/images/gnb-global/tv-A-4-1.jpg"
																												class="lazyload" alt="">
																										</div>
																										<div class="text">
																											<div class="title">LG SIGNATURE OLED 8K TV,</div>
																											<div class="desc">Nothing compares to LG OLED</div>
																										</div>
																									</a>
																								</div>
																								<div class="item">
																									<a href="https://www.lg.com/uk/soundbars"
																										data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																										data-link-name="Revolution in Sound">
																										<div class="image">
																											<img
																												data-src="https://www.lg.com/uk/images/gnb-global/tv-A-4-2.jpg"
																												class="lazyload" alt="">
																										</div>
																										<div class="text">
																											<div class="title">Revolution in Sound</div>
																											<div class="desc">Supreme Sound Bar</div>
																										</div>
																									</a>
																								</div>
																								<div class="item">
																									<a href="https://www.lg.com/uk/lgxboom/main.jsp"
																										data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																										data-link-name="Balanced &amp; Clear Sound" target="_blank"
																										title="Opens in a new window">
																										<div class="image">
																											<img
																												data-src="https://www.lg.com/uk/images/gnb-global/cav-A-4-2-xboom.jpg"
																												class="lazyload" alt="">
																										</div>
																										<div class="text">
																											<div class="title">Balanced &amp; Clear Sound</div>
																											<div class="desc">XBOOM Go</div>
																										</div>
																									</a>
																								</div>
																							</div>
																							<div class="slick-dot-wrap">
																								<div class="dot-box"></div>
																								<a href="#none" class="slide-pause pause" data-title-stop="Stop"
																									data-title-play="Play" role="button">Stop</a>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																			<div class="close"><a href="#"><span class="sr-only">Close the category navigation
																						menu</span></a></div>
																		</div>
																	</li>
																	<li><a href="https://www.lg.com/uk/appliances" data-id="gnbNV00012029"
																			data-link-area="gnb-b2c_primary_navigation_items"
																			data-link-name="appliances"><span>Appliances</span></a>
																		<div class="sublayer" id="gnbNV00012029">
																			<div class="skip_nav"><a href="#" role="button">Skip to Next Menu</a></div>
																			<div class="sublayer-inner">
																				<div class="columns">
																					<div class="column">
																						<div class="head-link" itemprop="name"><a
																								href="https://www.lg.com/uk/appliances" itemprop="url"
																								data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																								data-link-name="appliances">Appliances</a></div>
																						<ul>
																							<li class="sub-link"><a href="https://www.lg.com/uk/washing-machines"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="washing_machines">Washing Machines</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/washer-dryers"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="washer_dryers">Washer Dryers</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/tumble-dryers"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="tumble_dryers">Tumble Dryers</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/styler"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="styler">Styler</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/fridge-freezers"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="fridge_freezers">Fridge Freezers</a>
																								<ul class="link-list">
																									<li class="link"><a
																											href="https://www.lg.com/uk/instaview-door-in-door-fridge-freezers"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="instaview-door-in-door-fridge-freezers">InstaView
																											Door-in-Door™</a></li>
																								</ul>
																							</li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/winecellar"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="wine_cellar">Wine Cellar</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/heating-awhp"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="heating_solution_(awhp)">Heating Solution (AWHP)</a>
																							</li>
																							<li class="sub-link"><a
																									href="https://www.lg.com/uk/business/air-conditioning-systems/residential-air-conditioner"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="residential_air_conditioning">Residential Air
																									Conditioning</a></li>
																						</ul>
																					</div>
																					<div class="column">
																						<ul>
																							<li class="head-link">
																								<div>Discover</div>
																								<ul class="link-list">
																									<li class="link"><a
																											href="https://www.lg.com/uk/washing-machines/steam"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="lg_steam_washing_machine">LG Steam Washing
																											Machine</a></li>
																									<li class="link"><a
																											href="https://www.lg.com/uk/appliances/care-for-what-you-wear-2021"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="#careforwhatyouwear">#CareForWhatYouWear</a></li>
																									<li class="link"><a
																											href="https://www.lg.com/uk/healthy-home-solution/eat"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="smart_sustainable_living">Smart Sustainable
																											Living</a></li>
																								</ul>
																							</li>
																						</ul>
																					</div>
																					<div class="column banner">
																						<a href="https://www.lg.com/uk/appliances/thinq"
																							data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner"
																							data-link-name="ha_thinq_promotion" class="">
																							<div class="banner-visual outside">
																								<img
																									data-src="https://www.lg.com/uk/images/gnb-global/HA-ThinQ-Promotion-Banner.jpg"
																									class="lazyload" alt="">
																								<div class="banner-readmore active">
																									<div class="banner-more">
																										<span>Read More</span>
																									</div>
																								</div>
																							</div>
																						</a>
																					</div>
																					<div class="column featured-product">
																						<div class="gnb-feature">
																							<div class="feature-box"
																								data-wa-msg="Main Product ##1 in Appliances Category ">
																								<div class="item">
																									<a href="https://www.lg.com/uk/washing-machines/steam"
																										data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																										data-link-name="LG Steam Washing Machine">
																										<div class="image">
																											<img
																												data-src="https://www.lg.com/uk/images/gnb-global/ha-A-4-1.jpg"
																												class="lazyload" alt="">
																										</div>
																										<div class="text">
																											<div class="title">LG Steam Washing Machine</div>
																											<div class="desc">For the Ultimate Clean, Try Steam Care</div>
																										</div>
																									</a>
																								</div>
																							</div>
																							<div class="slick-dot-wrap">
																								<div class="dot-box"></div>
																								<a href="#none" class="slide-pause pause" data-title-stop="Stop"
																									data-title-play="Play" role="button">Stop</a>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																			<div class="close"><a href="#"><span class="sr-only">Close the category navigation
																						menu</span></a></div>
																		</div>
																	</li>
																	<li><a href="https://www.lg.com/uk/computer-products" data-id="gnbNV00012041"
																			data-link-area="gnb-b2c_primary_navigation_items"
																			data-link-name="computer_products"><span>Computer Products</span></a>
																		<div class="sublayer" id="gnbNV00012041">
																			<div class="skip_nav"><a href="#" role="button">Skip to Next Menu</a></div>
																			<div class="sublayer-inner">
																				<div class="columns">
																					<div class="column">
																						<div class="head-link" itemprop="name"><a
																								href="https://www.lg.com/uk/computer-products" itemprop="url"
																								data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																								data-link-name="computer_products">Computer Products</a></div>
																						<ul>
																							<li class="sub-link"><a href="https://www.lg.com/uk/monitors"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="monitors">Monitors</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/laptops"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="laptops">Laptops</a></li>
																						</ul>
																					</div>
																					<div class="column">
																						<ul>
																							<li class="head-link">
																								<div>Discover</div>
																								<ul class="link-list">
																									<li class="link"><a href="https://www.lg.com/uk/ultra_monitor/main"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="see_more._do_more._clearly">See More. Do More.
																											Clearly</a></li>
																								</ul>
																							</li>
																							<ul>
																								<li class="sub-link"><span class="no-link">Buying Guide</span>
																									<ul class="link-list">
																										<li class="link"><a
																												href="https://www.lg.com/uk/monitor-buying-guide"
																												data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																												data-link-name="monitors">Monitors</a></li>
																										<li class="link"><a href="https://www.lg.com/uk/laptop-buying-guide"
																												data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																												data-link-name="laptops">Laptops</a></li>
																									</ul>
																								</li>
																							</ul>
																						</ul>
																					</div>
																					<div class="column banner">
																						<a href="https://www.facebook.com/groups/hustlehubgram.uk"
																							data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner"
																							data-link-name="hustle_the_right_way!__hustle_hub_by_lg_gram"
																							target="_blank" title="Opens in a new window" class="white">
																							<div class="banner-visual outside">
																								<img
																									data-src="https://www.lg.com/uk/images/gnb-global/pc-gram-hustle-gnb-banner-big-02.jpg"
																									class="lazyload" alt="">
																								<div class="banner-description bottom">
																									<div class="banner-desc">It's Time to Hustle the Right Way!</div>
																									<div class="banner-head">Hustle Hub by LG gram</div>
																									<div class="banner-link">
																										<span>JOIN NOW</span>
																									</div>
																								</div>
																							</div>
																						</a>
																					</div>
																					<div class="column featured-product">
																						<div class="gnb-feature">
																							<div class="feature-box"
																								data-wa-msg="Main Product ##1 in Computer Products Category ">
																								<div class="item">
																									<a href="https://www.facebook.com/groups/hustlehubgram.uk"
																										data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																										data-link-name="It's Time to Hustle the Right Way! " target="_blank"
																										title="Opens in a new window">
																										<div class="image">
																											<img
																												data-src="https://www.lg.com/uk/images/gnb-global/pc-gram-hustle-gnb-banner-small.jpg"
																												class="lazyload" alt="">
																										</div>
																										<div class="text">
																											<div class="title">It's Time to Hustle the Right Way! </div>
																											<div class="desc">Hustle Hub by LG gram</div>
																										</div>
																									</a>
																								</div>
																								<div class="item">
																									<a href="https://www.lg.com/uk/gaming-monitors"
																										data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																										data-link-name="Geared Up for Victory">
																										<div class="image">
																											<img
																												data-src="https://www.lg.com/uk/images/gnb-global/it-A-4-1.jpg"
																												class="lazyload" alt="">
																										</div>
																										<div class="text">
																											<div class="title">Geared Up for Victory</div>
																											<div class="desc">LG UltraGear™ Gaming Monitor</div>
																										</div>
																									</a>
																								</div>
																								<div class="item">
																									<a href="https://www.lg.com/uk/mylg/product-registration"
																										data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																										data-link-name="Register your LG Products">
																										<div class="image">
																											<img
																												data-src="https://www.lg.com/uk/images/gnb-global/UK-computer-products-register-GNB_01.jpg"
																												class="lazyload" alt="">
																										</div>
																										<div class="text">
																											<div class="title">Register your LG Products</div>
																											<div class="desc">For helpful information, product support, and
																												much more.</div>
																										</div>
																									</a>
																								</div>
																							</div>
																							<div class="slick-dot-wrap">
																								<div class="dot-box"></div>
																								<a href="#none" class="slide-pause pause" data-title-stop="Stop"
																									data-title-play="Play" role="button">Stop</a>
																							</div>
																						</div>
																					</div>
																				</div>
																			</div>
																			<div class="close"><a href="#"><span class="sr-only">Close the category navigation
																						menu</span></a></div>
																		</div>
																	</li>
																	<li><a href="https://www.lg.com/uk/lg-experience" data-id="gnbNV00002295"
																			data-link-area="gnb-b2c_primary_navigation_items"
																			data-link-name="lg_experience"><span>LG EXPERIENCE</span></a>
																		<div class="sublayer" id="gnbNV00002295">
																			<div class="skip_nav"><a href="#" role="button">Skip to Next Menu</a></div>
																			<div class="sublayer-inner">
																				<div class="columns">
																					<div class="column">
																						<div class="head-link" itemprop="name"><a
																								href="https://www.lg.com/uk/lg-experience" itemprop="url"
																								data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																								data-link-name="lg_experience">LG EXPERIENCE</a></div>
																						<ul>
																							<li class="sub-link"><a
																									href="https://www.lg.com/uk/lg-experience/up-coming"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="up_&amp;_coming">Up &amp; Coming</a></li>
																							<li class="sub-link"><a
																									href="https://www.lg.com/uk/lg-experience/helpful-hints"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="helpful_hints">Helpful Hints</a></li>
																							<li class="sub-link"><a href="https://www.lg.com/uk/lg-experience/lg-lab"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="lg_lab">LG Lab</a></li>
																							<li class="sub-link"><a
																									href="https://www.lg.com/uk/lg-experience/inspiration"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="inspiration">Inspiration</a></li>
																							<li class="sub-link"><a
																									href="https://www.lg.com/uk/lg-experience/our-stories"
																									data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																									data-link-name="our_stories">Our Stories</a></li>
																						</ul>
																					</div>
																					<div class="column">
																						<ul>
																							<li class="head-link">
																								<div>FEATURED STORIES</div>
																								<ul class="link-list">
																									<li class="link"><a
																											href="https://www.lg.com/uk/lg-experience/up-coming/the-better-life-you-deserve-at-ces-2022"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="ces_2022_showcases_the_better_life_you_deserve">CES
																											2022 Showcases the Better Life You Deserve</a></li>
																									<li class="link"><a
																											href="https://www.lg.com/uk/lg-experience/helpful-hints/3-conscious-tips-for-a-better-you-in-2022"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="3_conscious_tips_for_a_better_you_in_2022">3
																											Conscious Tips for a Better You in 2022</a></li>
																									<li class="link"><a
																											href="https://www.lg.com/uk/lg-experience/up-coming/lg-holiday-season-gift-guide"
																											data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																											data-link-name="make_this_year’s_holiday_season_merry_and_bright_with_these_lg_gifts">Make
																											this year’s holiday season merry and bright with these LG
																											gifts</a></li>
																								</ul>
																							</li>
																						</ul>
																					</div>
																					<div class="column banner">
																						<a href="https://www.lg.com/uk/lg-experience/our-stories/eco-friendly-products-commitments"
																							data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner"
																							data-link-name="innovation_for_a_better_planet" target="_blank"
																							title="Opens in a new window" class="white">
																							<div class="banner-visual outside">
																								<img data-src="https://www.lg.com/uk/images/gnb-global/mag-A-3.jpg"
																									class="lazyload" alt="">
																								<div class="banner-description bottom">
																									<div class="banner-desc"></div>
																									<div class="banner-head">Innovation for a better planet</div>
																									<div class="banner-link">
																										<span>LEARN MORE</span>
																									</div>
																								</div>
																							</div>
																						</a>
																					</div>
																					<div class="column featured-product">
																					</div>
																				</div>
																			</div>
																			<div class="close"><a href="#"><span class="sr-only">Close the category navigation
																						menu</span></a></div>
																		</div>
																	</li>
																</ul>
																<div class="scroll-right"><a href="#"><span class="sr-only">Next</span></a></div>
															</div>
														</li>
														<li><a href="https://www.lg.com/uk/support" data-id="gnbNV00012056"
																data-link-area="gnb-b2c_primary_navigation_items"
																data-link-name="support"><span>Support</span></a>
															<div class="sublayer" id="gnbNV00012056">
																<div class="skip_nav"><a href="#" role="button">Skip to Next Menu</a></div>
																<div class="sublayer-inner">
																	<div class="columns support">
																		<div class="column">
																			<div class="head-link" itemprop="name"><a href="https://www.lg.com/uk/support"
																					itemprop="url" data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																					data-link-name="support">Support</a></div>
																			<ul>
																				<li class="head-link"><a
																						href="https://www.lg.com/uk/support/register-product-gate"
																						data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																						data-link-name="register_a_product">Register a Product</a>
																				</li>
																				<li class="head-link">
																					<div>
																						Downloads</div>
																					<ul class="link-list">
																						<li class="link"><a href="https://www.lg.com/uk/support/manuals"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="manuals">Manuals</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/software-firmware"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="software_&amp;_firmware">Software &amp; Firmware</a>
																						</li>
																						<li class="link"><a href="https://www.lg.com/uk/support/smart-share"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="smart_share">Smart Share</a></li>
																					</ul>
																				</li>
																			</ul>
																		</div>
																		<div class="column">
																			<ul>
																				<li class="head-link">
																					<div>
																						Guides</div>
																					<ul class="link-list">
																						<li class="link"><a href="https://www.lg.com/uk/support/product-help"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="searchable_help_articles">Searchable Help Articles</a>
																						</li>
																						<li class="link"><a href="https://www.lg.com/uk/support/video-tutorials"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="video_tutorials">Video Tutorials</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/smart-diagnosis"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="smart_diagnosis">Smart Diagnosis</a></li>
																					</ul>
																				</li>
																			</ul>
																		</div>
																		<div class="column">
																			<ul>
																				<li class="head-link"><a href="https://www.lg.com/uk/support/contact/whatsapp"
																						data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																						data-link-name="support_via_whatsapp">Support via WhatsApp</a>
																				</li>
																				<li class="head-link">
																					<div>
																						Contact</div>
																					<ul class="link-list">
																						<li class="link"><a href="https://www.lg.com/uk/support/chat-email"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="chat_&amp;_email">Chat &amp; Email</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/telephone"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="telephone">Telephone</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/inquiry-status"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="inquiry_status">Inquiry Status</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/web-survey"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="customer_feedback">Customer Feedback</a></li>
																					</ul>
																				</li>
																			</ul>
																		</div>
																		<div class="column">
																			<ul>
																				<li class="head-link">
																					<div>
																						Repair &amp; Warranty</div>
																					<ul class="link-list">
																						<li class="link"><a
																								href="https://www.lg.com/uk/support/repair-warranty/request-repair"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="request_a_repair">Request a Repair</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/warranty"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="warranty">Warranty</a></li>
																						<li class="link"><a
																								href="https://www.lg.com/uk/support/repair-warranty/business-warranty"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="business_warranty">Business Warranty</a></li>
																					</ul>
																				</li>
																			</ul>
																		</div>
																		<div class="column">
																			<ul>
																				<li class="head-link">
																					<div>
																						Additional Support</div>
																					<ul class="link-list">
																						<li class="link"><a href="http://www.4lg.co.uk/"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="parts_&amp;_accessories" target="_blank"
																								title="Opens in a new window">Parts &amp; Accessories</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/announcements"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="announcements">Announcements</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/lg-environmental"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="environmental">Environmental</a></li>
																						<li class="link"><a href="https://www.lg.com/uk/support/document-attachment"
																								data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																								data-link-name="document_upload">Document Upload</a></li>
																					</ul>
																				</li>
																			</ul>
																		</div>
																		<div class="column">
																			<ul class="link-list">
																				<li class="link"><a href="https://www.lg.com/uk/my-lg/my-profile"
																						data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																						data-link-name="my_profile">My Profile</a></li>
																				<li class="link"><a href="https://www.lg.com/uk/my-lg/my-products"
																						data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																						data-link-name="my_products">My Products</a></li>
																				<li class="link"><a href="https://www.lg.com/uk/my-lg/my-inquiry-status-list"
																						data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																						data-link-name="my_inquiry_status">My Inquiry Status</a></li>
																			</ul>
																		</div>
																		<div class="column">
																			<ul>
																				<li class="head-link"><a href="https://www.lg.com/uk/support/right-to-repair"
																						data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																						data-link-name="right_to_repair">Right To Repair</a>
																				</li>
																			</ul>
																		</div>
																		<div class="column">
																			<ul>
																				<li class="head-link"><a href="https://www.lg.com/uk/shop/sales/guest/form/"
																						data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																						data-link-name="track_my_order">Online Shop: Track My Order</a>
																				</li>
																				<li class="head-link"><a href="https://www.lg.com/uk/shop/faq"
																						data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																						data-link-name="frequently_asked_questions_-_faq">ONLINE SHOP: FAQ</a>
																				</li>
																			</ul>
																		</div>
																	</div>
																</div>
																<div class="close"><a href="#"><span class="sr-only">Close the category navigation
																			menu</span></a></div>
															</div>
														</li>
													</ul>
													<div class="tablet-layer"></div>
												</div>
												<div class="right-btm">
													<ul class="icons">
														<li class="login"><a href="#"><span class="sr-only">My LG</span></a>
															<div class="gnb-login">
																<div class="before-login">
																	<ul>
																		<li><a href="https://www.lg.com/uk/my-lg/login?state=/uk/my-lg" class="before-login"
																				data-link-area="gnb-utility_menu" data-link-name="sign_in_sign_up">Sign In /
																				Sign Up</a></li>
																		<li><a href="https://www.lg.com/uk/support/register-product-gate"
																				class="before-login" data-link-area="gnb-utility_menu"
																				data-link-name="Register a Product">Register a Product</a></li>
																	</ul>
																</div>
																<div class="after-login">
																	<div class="welcome"> Welcome&nbsp;<span class="name"></span> </div>
																	<div class="box-obs">
																		<div class="box-coupon"><a
																				href="https://www.lg.com/uk/shop/multicoupon/mycoupon/couponlist/"
																				target="_blank" title="Opens in a new window" data-link-area="gnb-utility_menu"
																				data-link-name="available_coupons">
																				<ul>
																					<li class="title">Available Voucher</li>
																					<li class="number"></li>
																				</ul>
																			</a></div>
																	</div>
																	<ul>
																		<li><a href="https://www.lg.com/uk/my-lg/my-support"
																				data-link-area="gnb-utility_menu" data-link-name="My LG">My LG</a></li>
																		<li><a href="https://www.lg.com/uk/shop/sales/order/history/"
																				data-link-area="gnb-utility_menu" data-link-name="My Orders">My Orders</a></li>
																		<li><a href="https://www.lg.com/uk/my-lg/my-profile"
																				data-link-area="gnb-utility_menu" data-link-name="My Profile">My Profile</a>
																		</li>
																		<li><a href="https://www.lg.com/uk/my-lg/my-products"
																				data-link-area="gnb-utility_menu" data-link-name="My Products">My Products</a>
																		</li>
																		<li><a href="https://www.lg.com/uk/my-lg/my-inquiry-status-list"
																				data-link-area="gnb-utility_menu" data-link-name="My Inquiries">My Inquiries</a>
																		</li>
																		<li><a href="https://www.lg.com/uk/support/register-product-gate"
																				data-link-area="gnb-utility_menu" data-link-name="Register a Product">Register a
																				Product</a></li>
																		<li><a href="https://www.lg.com/uk/my-lg/logout?state=/uk/mylg/login"
																				data-link-area="gnb-utility_menu" data-link-name="Sign Out">Sign Out</a></li>
																	</ul>
																</div>
															</div>
														</li>
														<li class="cart" data-alert-success="Successfully added to your basket"
															data-pre-order-success="Successfully added to your Pre-Order cart."
															data-alert-btn="View Basket"
															data-cookie-notice-msg="“We use the cookies to proceed your purchase.” "
															data-close-btn="CONTINUE SHOPPING"><a
																href="https://www.lg.com/uk/shop/checkout/cart/index" data-link-area="gnb-utility_menu"
																data-link-name="cart"><span class="sr-only">Cart</span><span class="count"></span></a>
														</li>
														<li class="search"><a href="#navigation_search" data-link-area="gnb-utility_menu"
																data-link-name="search"><span class="sr-only">Search</span></a></li>
													</ul>
												</div>
											</div>
										</nav>
									</div>
								</div>
								<div class="row for-mobile  ">
									<div class="top-menu">
										<ul>
											<li class="active"><a href="https://www.lg.com/uk" data-link-area="gnb-consumer_toggle"
													data-link-name="consumer"><span>Consumer</span></a></li>
											<li><a href="https://www.lg.com/uk/business" data-link-area="gnb-business_toggle"
													data-link-name="business"><span>Business</span></a></li>
										</ul>
									</div>
									<div class="nav-wrap">
										<div class="logo"> <a href="https://www.lg.com/uk"><img
													src="https://www.lg.com/lg5-common-gp/images/common/header/logo-b2c-m.jpg"
													data-link-area="gnb_brand_identity" data-link-name="" alt="LG logo"></a> </div>
										<div class="menu"> <a href="#" data-link-area="gnb-hamburger_menu"
												data-link-name="hamburger_menu"><span class="line line1"></span><span
													class="line line2"></span><span class="line line3"></span><span
													class="sr-only">Menu</span></a>
											<nav class="menu-wrap">
												<ul class="top-link active">
													<li><a href="https://www.lg.com/uk/lg-signature" data-link-area="gnb-lg_brand_logo"
															data-link-name="lg_signature"><img
																src="https://www.lg.com/uk/images/gnb-global/lg-signature-logo.png" alt=""></a>
													</li>
												</ul>
												<ul class="depth1-m active">
													<li><a href="#gnbNV00012003M" data-link-area="gnb-b2c_primary_navigation_items"
															data-link-name="tv/audio/video">TV/Audio/Video</a></li>
													<li><a href="#gnbNV00012029M" data-link-area="gnb-b2c_primary_navigation_items"
															data-link-name="appliances">Appliances</a></li>
													<li><a href="#gnbNV00012041M" data-link-area="gnb-b2c_primary_navigation_items"
															data-link-name="computer_products">Computer Products</a></li>
													<li><a href="#gnbNV00002295M" data-link-area="gnb-b2c_primary_navigation_items"
															data-link-name="lg_experience">LG EXPERIENCE</a></li>
													<li class="support"><a href="#gnbNV00012056M"
															data-link-area="gnb-b2c_primary_navigation_items" data-link-name="support">Support</a>
													</li>
												</ul>
												<div class="sublayer-m" id="gnbNV00012003M">
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
													<ul class="depth2-m">
														<li class="type1"><a href="https://www.lg.com/uk/tv-audio-video"
																data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																data-link-name="tv/audio/video">TV/Audio/Video</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/tvs"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link" data-link-name="tvs">TVs</a>
														</li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/global/lg-signature/rollable-oled-tv-r"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="rollable_oled_tv" target="_blank"
																		title="Opens in a new window">Rollable OLED TV</a></li>
																<li><a href="https://www.lg.com/uk/oled-tvs"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="oled_tvs">OLED TVs</a></li>
																<li><a href="https://www.lg.com/uk/qned-tvs"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="qned_miniled_tvs">QNED MiniLED TVs</a></li>
																<li><a href="https://www.lg.com/uk/nanocell-tvs"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="nanocell_tvs">NanoCell TVs</a></li>
																<li><a href="https://www.lg.com/uk/ultra-large-tvs"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="ultra_large_tvs">Ultra Large TVs</a></li>
																<li><a href="https://www.lg.com/uk/ultra-hd-4k-tvs"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="uhd_4k_tvs">UHD 4K TVs</a></li>
																<li><a href="https://www.lg.com/uk/smart-tvs"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="smart_tvs">Smart TVs</a></li>
																<li><a href="https://www.lg.com/uk/led-tvs"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="led_tvs">LED TVs</a></li>
															</ul>
														</li>
														<li class="type2"><a href="https://www.lg.com/uk/speakers-sound-systems"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="speakers_&amp;_sound_systems">Speakers &amp; Sound Systems</a></li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/gaming-speakers"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="gaming-speakers">Gaming Speakers</a></li>
															</ul>
														</li>
														<li class="type2"><a href="https://www.lg.com/uk/true-wireless-earbuds"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="true_wireless_earbuds">True Wireless Earbuds</a></li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/bacteria-killing-earbuds"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="bacteria-killing_earbuds">Bacteria-killing Earbuds</a></li>
																<li><a href="https://www.lg.com/uk/active-noise-cancelling-earbuds"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="active_noise_cancelling_earbuds">Active Noise Cancelling Earbuds</a>
																</li>
															</ul>
														</li>
														<li class="type2"><a href="https://www.lg.com/uk/blu-ray-dvd-players"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="blu-ray-dvd_players">Blu-ray &amp; DVD Players</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/projectors"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="projectors">PROJECTORS</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/home-cinema-systems"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="home_cinema_systems">Home Cinema Systems</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/tv-accessories"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="tv_accessories">TV Accessories</a></li>
														<li class="type2 discover"><span class="no-link">Buying Guide</span></li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/projector-buying-guide"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="projector">Projector</a></li>
															</ul>
														</li>
													</ul>
													<div class="column banner">
														<a href="https://www.lg.com/uk/true-wireless-earbuds/2021/tonefree"
															data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner" data-link-name="lg-tone-ufp9"
															class="white">
															<div class="banner-visual outside">
																<img data-src="https://www.lg.com/uk/images/gnb-global/LG_TONEFree_UFP9_GNB_UK.jpg"
																	class="lazyload" alt="">
																<div class="banner-description bottom">
																	<div class="banner-desc"></div>
																	<div class="banner-head"></div>
																	<div class="banner-link">
																		<span>Find Out More</span>
																	</div>
																</div>
															</div>
														</a>
													</div>
													<div class="column featured-product">
														<div class="gnb-feature">
															<div class="feature-box" data-wa-msg="Main Product ##1 in TV/Audio/Video Category ">
																<div class="item">
																	<a href="https://www.lg.com/uk/tvs/lg-oled88z19la"
																		data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																		data-link-name="LG SIGNATURE OLED 8K TV,">
																		<div class="image">
																			<img data-src="https://www.lg.com/uk/images/gnb-global/tv-A-4-1.jpg"
																				class="lazyload" alt="">
																		</div>
																		<div class="text">
																			<div class="title">LG SIGNATURE OLED 8K TV,</div>
																			<div class="desc">Nothing compares to LG OLED</div>
																		</div>
																	</a>
																</div>
																<div class="item">
																	<a href="https://www.lg.com/uk/soundbars"
																		data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																		data-link-name="Revolution in Sound">
																		<div class="image">
																			<img data-src="https://www.lg.com/uk/images/gnb-global/tv-A-4-2.jpg"
																				class="lazyload" alt="">
																		</div>
																		<div class="text">
																			<div class="title">Revolution in Sound</div>
																			<div class="desc">Supreme Sound Bar</div>
																		</div>
																	</a>
																</div>
																<div class="item">
																	<a href="https://www.lg.com/uk/lgxboom/main.jsp"
																		data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																		data-link-name="Balanced &amp; Clear Sound" target="_blank"
																		title="Opens in a new window">
																		<div class="image">
																			<img data-src="https://www.lg.com/uk/images/gnb-global/cav-A-4-2-xboom.jpg"
																				class="lazyload" alt="">
																		</div>
																		<div class="text">
																			<div class="title">Balanced &amp; Clear Sound</div>
																			<div class="desc">XBOOM Go</div>
																		</div>
																	</a>
																</div>
															</div>
															<div class="slick-dot-wrap">
																<div class="dot-box"></div>
																<a href="#none" class="slide-pause pause" data-title-stop="Stop" data-title-play="Play"
																	role="button">Stop</a>
															</div>
														</div>
													</div>
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
												</div>
												<div class="sublayer-m" id="gnbNV00012029M">
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
													<ul class="depth2-m">
														<li class="type1"><a href="https://www.lg.com/uk/appliances"
																data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																data-link-name="appliances">Appliances</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/washing-machines"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="washing_machines">Washing Machines</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/washer-dryers"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="washer_dryers">Washer Dryers</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/tumble-dryers"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="tumble_dryers">Tumble Dryers</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/styler"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="styler">Styler</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/fridge-freezers"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="fridge_freezers">Fridge Freezers</a></li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/instaview-door-in-door-fridge-freezers"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="instaview-door-in-door-fridge-freezers">InstaView Door-in-Door™</a>
																</li>
															</ul>
														</li>
														<li class="type2"><a href="https://www.lg.com/uk/winecellar"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="wine_cellar">Wine Cellar</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/heating-awhp"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="heating_solution_(awhp)">Heating Solution (AWHP)</a></li>
														<li class="type2"><a
																href="https://www.lg.com/uk/business/air-conditioning-systems/residential-air-conditioner"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="residential_air_conditioning">Residential Air Conditioning</a></li>
														<li class="type1 discover"><span class="no-link">Discover</span></li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/washing-machines/steam"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="lg_steam_washing_machine">LG Steam Washing Machine</a></li>
																<li><a href="https://www.lg.com/uk/appliances/care-for-what-you-wear-2021"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="#careforwhatyouwear">#CareForWhatYouWear</a></li>
																<li><a href="https://www.lg.com/uk/healthy-home-solution/eat"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="smart_sustainable_living">Smart Sustainable Living</a></li>
															</ul>
														</li>
													</ul>
													<div class="column banner">
														<a href="https://www.lg.com/uk/appliances/thinq"
															data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner"
															data-link-name="ha_thinq_promotion" class="">
															<div class="banner-visual outside">
																<img data-src="https://www.lg.com/uk/images/gnb-global/HA-ThinQ-Promotion-Banner.jpg"
																	class="lazyload" alt="">
																<div class="banner-readmore active">
																	<div class="banner-more">
																		<span>Read More</span>
																	</div>
																</div>
															</div>
														</a>
													</div>
													<div class="column featured-product">
														<div class="gnb-feature">
															<div class="feature-box" data-wa-msg="Main Product ##1 in Appliances Category ">
																<div class="item">
																	<a href="https://www.lg.com/uk/washing-machines/steam"
																		data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																		data-link-name="LG Steam Washing Machine">
																		<div class="image">
																			<img data-src="https://www.lg.com/uk/images/gnb-global/ha-A-4-1.jpg"
																				class="lazyload" alt="">
																		</div>
																		<div class="text">
																			<div class="title">LG Steam Washing Machine</div>
																			<div class="desc">For the Ultimate Clean, Try Steam Care</div>
																		</div>
																	</a>
																</div>
															</div>
															<div class="slick-dot-wrap">
																<div class="dot-box"></div>
																<a href="#none" class="slide-pause pause" data-title-stop="Stop" data-title-play="Play"
																	role="button">Stop</a>
															</div>
														</div>
													</div>
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
												</div>
												<div class="sublayer-m" id="gnbNV00012041M">
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
													<ul class="depth2-m">
														<li class="type1"><a href="https://www.lg.com/uk/computer-products"
																data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																data-link-name="computer_products">Computer Products</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/monitors"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="monitors">Monitors</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/laptops"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="laptops">Laptops</a></li>
														<li class="type1 discover"><span class="no-link">Discover</span></li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/ultra_monitor/main"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="see_more._do_more._clearly">See More. Do More. Clearly</a></li>
															</ul>
														</li>
														<li class="type2 discover"><span class="no-link">Buying Guide</span></li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/monitor-buying-guide"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="monitors">Monitors</a></li>
																<li><a href="https://www.lg.com/uk/laptop-buying-guide"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="laptops">Laptops</a></li>
															</ul>
														</li>
													</ul>
													<div class="column banner">
														<a href="https://www.facebook.com/groups/hustlehubgram.uk"
															data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner"
															data-link-name="hustle_the_right_way!__hustle_hub_by_lg_gram" target="_blank"
															title="Opens in a new window" class="white">
															<div class="banner-visual outside">
																<img
																	data-src="https://www.lg.com/uk/images/gnb-global/pc-gram-hustle-gnb-banner-big-02.jpg"
																	class="lazyload" alt="">
																<div class="banner-description bottom">
																	<div class="banner-desc">It's Time to Hustle the Right Way!</div>
																	<div class="banner-head">Hustle Hub by LG gram</div>
																	<div class="banner-link">
																		<span>JOIN NOW</span>
																	</div>
																</div>
															</div>
														</a>
													</div>
													<div class="column featured-product">
														<div class="gnb-feature">
															<div class="feature-box" data-wa-msg="Main Product ##1 in Computer Products Category ">
																<div class="item">
																	<a href="https://www.facebook.com/groups/hustlehubgram.uk"
																		data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																		data-link-name="It's Time to Hustle the Right Way! " target="_blank"
																		title="Opens in a new window">
																		<div class="image">
																			<img
																				data-src="https://www.lg.com/uk/images/gnb-global/pc-gram-hustle-gnb-banner-small.jpg"
																				class="lazyload" alt="">
																		</div>
																		<div class="text">
																			<div class="title">It's Time to Hustle the Right Way! </div>
																			<div class="desc">Hustle Hub by LG gram</div>
																		</div>
																	</a>
																</div>
																<div class="item">
																	<a href="https://www.lg.com/uk/gaming-monitors"
																		data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																		data-link-name="Geared Up for Victory">
																		<div class="image">
																			<img data-src="https://www.lg.com/uk/images/gnb-global/it-A-4-1.jpg"
																				class="lazyload" alt="">
																		</div>
																		<div class="text">
																			<div class="title">Geared Up for Victory</div>
																			<div class="desc">LG UltraGear™ Gaming Monitor</div>
																		</div>
																	</a>
																</div>
																<div class="item">
																	<a href="https://www.lg.com/uk/mylg/product-registration"
																		data-link-area="gnb-b2c_exposed_mega_nav-feature_product"
																		data-link-name="Register your LG Products">
																		<div class="image">
																			<img
																				data-src="https://www.lg.com/uk/images/gnb-global/UK-computer-products-register-GNB_01.jpg"
																				class="lazyload" alt="">
																		</div>
																		<div class="text">
																			<div class="title">Register your LG Products</div>
																			<div class="desc">For helpful information, product support, and much more.</div>
																		</div>
																	</a>
																</div>
															</div>
															<div class="slick-dot-wrap">
																<div class="dot-box"></div>
																<a href="#none" class="slide-pause pause" data-title-stop="Stop" data-title-play="Play"
																	role="button">Stop</a>
															</div>
														</div>
													</div>
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
												</div>
												<div class="sublayer-m" id="gnbNV00002295M">
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
													<ul class="depth2-m">
														<li class="type1"><a href="https://www.lg.com/uk/lg-experience"
																data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																data-link-name="lg_experience">LG EXPERIENCE</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/lg-experience/up-coming"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="up_&amp;_coming">Up &amp; Coming</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/lg-experience/helpful-hints"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="helpful_hints">Helpful Hints</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/lg-experience/lg-lab"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link" data-link-name="lg_lab">LG
																Lab</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/lg-experience/inspiration"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																data-link-name="inspiration">Inspiration</a></li>
														<li class="type2"><a href="https://www.lg.com/uk/lg-experience/our-stories"
																data-link-area="gnb-b2c_exposed_mega_nav-category_link" data-link-name="our_stories">Our
																Stories</a></li>
														<li class="type1 discover"><span class="no-link">FEATURED STORIES</span></li>
														<li class="type3">
															<ul>
																<li><a
																		href="https://www.lg.com/uk/lg-experience/up-coming/the-better-life-you-deserve-at-ces-2022"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="ces_2022_showcases_the_better_life_you_deserve">CES 2022 Showcases
																		the Better Life You Deserve</a></li>
																<li><a
																		href="https://www.lg.com/uk/lg-experience/helpful-hints/3-conscious-tips-for-a-better-you-in-2022"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="3_conscious_tips_for_a_better_you_in_2022">3 Conscious Tips for a
																		Better You in 2022</a></li>
																<li><a href="https://www.lg.com/uk/lg-experience/up-coming/lg-holiday-season-gift-guide"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="make_this_year’s_holiday_season_merry_and_bright_with_these_lg_gifts">Make
																		this year’s holiday season merry and bright with these LG gifts</a></li>
															</ul>
														</li>
													</ul>
													<div class="column banner">
														<a href="https://www.lg.com/uk/lg-experience/our-stories/eco-friendly-products-commitments"
															data-link-area="gnb-b2c_exposed_mega_nav-promotion_banner"
															data-link-name="innovation_for_a_better_planet" target="_blank"
															title="Opens in a new window" class="white">
															<div class="banner-visual outside">
																<img data-src="https://www.lg.com/uk/images/gnb-global/mag-A-3.jpg" class="lazyload"
																	alt="">
																<div class="banner-description bottom">
																	<div class="banner-desc"></div>
																	<div class="banner-head">Innovation for a better planet</div>
																	<div class="banner-link">
																		<span>LEARN MORE</span>
																	</div>
																</div>
															</div>
														</a>
													</div>
													<div class="column featured-product">
													</div>
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
												</div>
												<div class="sublayer-m" id="gnbNV00012056M">
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
													<ul class="depth2-m">
														<li class="type1"><a href="https://www.lg.com/uk/support"
																data-link-area="gnb-b2b_exposed_mega_nav-supercategory_link"
																data-link-name="support">Support</a></li>
														<li class="type1">
															<ul>
																<li><a href="https://www.lg.com/uk/support/register-product-gate"
																		data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																		data-link-name="register_a_product">Register a Product</a></li>
															</ul>
														</li>
														<li class="type1">
															<ul>
																<li><span class="no-link">Downloads</span></li>
															</ul>
														</li>
														<li class="type3">
															<ul>
																<li><a href="https://www.lg.com/uk/support/manuals"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="manuals">Manuals</a></li>
																<li><a href="https://www.lg.com/uk/support/software-firmware"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="software_&amp;_firmware">Software &amp; Firmware</a></li>
																<li><a href="https://www.lg.com/uk/support/smart-share"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="smart_share">Smart Share</a></li>
															</ul>
														</li>
														<li class="expand"><a href="#none">Guides</a></li>
														<li class="sub">
															<ul>
																<li class="type3"><a href="https://www.lg.com/uk/support/product-help"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="searchable_help_articles">Searchable Help Articles</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/video-tutorials"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="video_tutorials">Video Tutorials</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/smart-diagnosis"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="smart_diagnosis">Smart Diagnosis</a></li>
															</ul>
														</li>
														<li class="no-expand"><a href="https://www.lg.com/uk/support/contact/whatsapp"
																data-link-area="gnb-b2c_exposed_mega_nav-supercategory_link"
																data-link-name="support_via_whatsapp">Support via WhatsApp</a></li>
														<li class="expand"><a href="#none">Contact</a></li>
														<li class="sub">
															<ul>
																<li class="type3"><a href="https://www.lg.com/uk/support/chat-email"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="chat_&amp;_email">Chat &amp; Email</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/telephone"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="telephone">Telephone</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/inquiry-status"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="inquiry_status">Inquiry Status</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/web-survey"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="customer_feedback">Customer Feedback</a></li>
															</ul>
														</li>
														<li class="expand"><a href="#none">Repair &amp; Warranty</a></li>
														<li class="sub">
															<ul>
																<li class="type3"><a href="https://www.lg.com/uk/support/repair-warranty/request-repair"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="request_a_repair">Request a Repair</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/warranty"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="warranty">Warranty</a></li>
																<li class="type3"><a
																		href="https://www.lg.com/uk/support/repair-warranty/business-warranty"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="business_warranty">Business Warranty</a></li>
															</ul>
														</li>
														<li class="expand"><a href="#none">Additional Support</a></li>
														<li class="sub">
															<ul>
																<li class="type3"><a href="http://www.4lg.co.uk/"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="parts_&amp;_accessories" target="_blank"
																		title="Opens in a new window">Parts &amp; Accessories</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/announcements"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="announcements">Announcements</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/lg-environmental"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="environmental">Environmental</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/support/document-attachment"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="document_upload">Document Upload</a></li>
															</ul>
														</li>
														<li class="sub">
															<ul>
																<li class="type3"><a href="https://www.lg.com/uk/my-lg/my-profile"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="my_profile">My Profile</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/my-lg/my-products"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="my_products">My Products</a></li>
																<li class="type3"><a href="https://www.lg.com/uk/my-lg/my-inquiry-status-list"
																		data-link-area="gnb-b2c_exposed_mega_nav-subcategory_link"
																		data-link-name="my_inquiry_status">My Inquiry Status</a></li>
																<li class="no-expand"><a href="https://www.lg.com/uk/support/right-to-repair"
																		data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																		data-link-name="right_to_repair">Right To Repair</a></li>
																<li class="no-expand"><a href="https://www.lg.com/uk/shop/sales/guest/form/"
																		data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																		data-link-name="track_my_order">Online Shop: Track My Order</a></li>
																<li class="no-expand"><a href="https://www.lg.com/uk/shop/faq"
																		data-link-area="gnb-b2c_exposed_mega_nav-category_link"
																		data-link-name="frequently_asked_questions_-_faq">ONLINE SHOP: FAQ</a></li>
															</ul>
															<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
														</li>
													</ul>
												</div>
												<ul class="mylg active">
													<li class="login"><a href="https://www.lg.com/uk/my-lg/login?state=/uk/my-lg"
															class="before-login" data-link-area="gnb-utility_menu" data-link-name="sign_in">Sign
															In</a><a href="https://www.lg.com/uk/my-lg/login?page=signup" class="before-login sign-up"
															data-link-area="gnb-utility_menu" data-link-name="sign_up">Sign Up</a><a
															href="#welcomeB2C" class="after-login">Welcome <span class="name"></span></a></li>
													<li class="btn-register-product"><a href="https://www.lg.com/uk/support/register-product-gate"
															class="before-login" data-link-area="gnb-utility_menu"
															data-link-name="Register a Product">Register a Product</a></li>
												</ul>
												<div class="box-obs">
													<div class="box-coupon"><a href="https://www.lg.com/uk/shop/multicoupon/mycoupon/couponlist/"
															target="_blank" title="Opens in a new window" data-link-area="gnb-utility_menu"
															data-link-name="available_coupons">
															<ul>
																<li class="title">Available Voucher</li>
																<li class="number"></li>
															</ul>
														</a></div>
												</div>
												<div class="sublayer-m" id="welcomeB2C">
													<div class="back"><a href="#"><span class="sr-only">Main Menu</span></a></div>
													<div class="welcome"> Welcome&nbsp;<span class="name"></span> </div>
													<div class="box-obs">
														<div class="box-coupon"><a
																href="https://www.lg.com/uk/shop/multicoupon/mycoupon/couponlist/" target="_blank"
																title="Opens in a new window" data-link-area="gnb-utility_menu"
																data-link-name="available_coupons">
																<ul>
																	<li class="title">Available Voucher</li>
																	<li class="number"></li>
																</ul>
															</a></div>
													</div>
													<ul class="depth2-m">
														<li class="type3"><a href="https://www.lg.com/uk/my-lg/my-support"
																data-link-area="gnb-utility_menu" data-link-name="My LG">My LG</a></li>
														<li class="type3"><a href="https://www.lg.com/uk/shop/sales/order/history/"
																data-link-area="gnb-utility_menu" data-link-name="My Orders">My Orders</a></li>
														<li class="type3"><a href="https://www.lg.com/uk/my-lg/my-profile"
																data-link-area="gnb-utility_menu" data-link-name="My Profile">My Profile</a></li>
														<li class="type3"><a href="https://www.lg.com/uk/my-lg/my-products"
																data-link-area="gnb-utility_menu" data-link-name="My Products">My Products</a></li>
														<li class="type3"><a href="https://www.lg.com/uk/my-lg/my-inquiry-status-list"
																data-link-area="gnb-utility_menu" data-link-name="My Inquiries">My Inquiries</a></li>
														<li class="type3"><a href="https://www.lg.com/uk/support/register-product-gate"
																data-link-area="gnb-utility_menu" data-link-name="Register a Product">Register a
																Product</a></li>
														<li class="type3"><a href="https://www.lg.com/uk/my-lg/logout?state=/uk/mylg/login"
																data-link-area="gnb-utility_menu" data-link-name="Sign Out">Sign Out</a></li>
													</ul>
												</div>
											</nav>
										</div>
										<div class="left">
											<div class="icons">
												<div class="search"><a href="#"><span class="sr-only">Search</span></a></div>
											</div>
										</div>
										<div class="right">
											<div class="icons">
												<div class="login"> <a href="https://www.lg.com/uk/my-lg/login?state=/uk/my-lg"
														class="before-login" data-link-area="gnb-utility_menu"
														data-link-name="sign_in_sign_up"><span class="sr-only">My LG</span></a><a href="#welcomeB2C"
														class="after-login"><span class="sr-only">Welcome</span></a> </div>
												<div class="cart" data-alert-success="Successfully added to your basket"
													data-pre-order-success="Successfully added to your Pre-Order cart."
													data-cookie-notice-msg="“We use the cookies to proceed your purchase.” "
													data-alert-btn="View Basket" data-close-btn="CONTINUE SHOPPING"><a
														href="https://www.lg.com/uk/shop/checkout/cart/index" data-link-area="gnb-utility_menu"
														data-link-name="cart"><span class="sr-only">Cart</span><span class="count"></span></a></div>
											</div>
										</div>
									</div>
								</div>
								<div class="the-search-window" id="navigation_search"
									data-child-html="https://www.lg.com/uk/gp/search/ajax/navigationSearch"> </div>
							</header>
							<nav class="breadcrumb">
								<ul itemscope itemtype="http://schema.org/BreadcrumbList">
									<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a href="/uk"
											itemprop="item" data-link-area="gnb-breadcrumb" data-link-name="home"><span
												itemprop="name">HOME</span></a>
										<meta itemprop="position" content="1">
									</li>
									<li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem"><a
											href="/uk/washing-machines" itemprop="item" data-link-area="gnb-breadcrumb"
											data-link-name="home_washing_machines"><span itemprop="name">Washing Machines</span></a>
										<meta itemprop="position" content="2">
									</li>
									<li><strong>LG Steam Washing Machine</strong></li>
								</ul>
							</nav>
						</div>


					</div>
					<div class="iw_component" id="iw_comp1596245554671">
						<div></div>
					</div>
				</div>
			</div>
		</div>